# Generated by Django 5.0.4 on 2024-04-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_toornament_prize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toornament',
            name='lead',
        ),
    ]
